### ISSUE TITLE
Missing bits of information.

### ISSUE THREAD

**Issue by jdeathe** [jedi58/ossus#1]
"A repository filled with useful bits of information and scripts". 📦

**Comment by jedi58** [comment]
@jdeathe ?

**Comment by jdeathe** [comment]
I can only see the README doc in there. What does ossus mean?

**Comment by jedi58** [comment]
@jdeathe I've not committed any of the files yet 😛

**Comment by jedi58** [comment]
First file is here: https://github.com/jedi58/ossus/blob/master/mac/cleanupDownloads.md

Ossus is the "Jedi Library" in the "Star Wars: Dark Empire" series from Dark Horse
