### ISSUE TITLE
Should include the header "Vary: Origin" when setting CORS header.

### ISSUE THREAD

**Issue by jdeathe** [jedi58/ossus#2]
- https://github.com/jedi58/ossus/blob/master/apache-httpd/allowCrossOriginByDomain.md

Ref: https://www.w3.org/TR/cors/#resource-implementation

> As a consequence, authors of such resources should send a Vary: Origin HTTP header or provide other appropriate control directives to prevent caching of such responses, which may be inaccurate if re-used across-origins.

**Comment by jedi58** [comment]
think in most cases this won't be cached - but will add this anyway for cases where it is needed

```apache
Header always set Vary Origin
```

**Comment by jedi58** [comment]
Changed in https://github.com/jedi58/ossus/commit/3112a942f229cb2c3f854b8f185d9efd6c2ae9d7
